package com.ironquestprep;

import java.util.*;

/** Generated from the local Quest Helper source snapshot, 2026-09-28. See skill-data-notes.md. */
final class GeneratedQuestSkills {
    static List<QuestSkillPlanner.QuestData> load() {
        List<QuestSkillPlanner.QuestData> rows = new ArrayList<>();
        rows.add(new QuestSkillPlanner.QuestData("A_KINGDOM_DIVIDED", true, "AGILITY:54,THIEVING:52,WOODCUTTING:52,HERBLORE:50,MINING:42,CRAFTING:38,MAGIC:35", "", "X_MARKS_THE_SPOT,THE_QUEEN_OF_THIEVES,THE_DEPTHS_OF_DESPAIR,THE_ASCENT_OF_ARCEUUS,THE_FORSAKEN_TOWER,TALE_OF_THE_RIGHTEOUS", 0, 2, "Check quest guide for access, items and other requirements.", "Antique Lamp (10,000 Exp. Any Skill level 40 or above.; Expanded access to the Arceuus spellbook."));
        rows.add(new QuestSkillPlanner.QuestData("A_NIGHT_AT_THE_THEATRE", true, "", "", "A_TASTE_OF_HOPE", 0, 2, "", "Antique Lamp (20,000 Exp. Any Combat Skill, excluding prayer)"));
        rows.add(new QuestSkillPlanner.QuestData("A_PORCINE_OF_INTEREST", true, "", "SLAYER:1000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("A_SOULS_BANE", true, "", "DEFENCE:500,HITPOINTS:500", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("A_TAIL_OF_TWO_CATS", true, "", "", "ICTHLARINS_LITTLE_HELPER", 0, 2, "", "2,500 Experience Lamps (Any skill over level 30)."));
        rows.add(new QuestSkillPlanner.QuestData("A_TASTE_OF_HOPE", true, "CRAFTING:48,AGILITY:45,ATTACK:40,HERBLORE:40,SLAYER:38", "", "DARKNESS_OF_HALLOWVALE", 0, 1, "", "2,500 Experience Tomes (Any skill over level 35)."));
        rows.add(new QuestSkillPlanner.QuestData("ALFRED_GRIMHANDS_BARCRAWL", false, "", "", "", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ANIMAL_MAGNETISM", true, "SLAYER:18,CRAFTING:19,RANGED:30,WOODCUTTING:35", "CRAFTING:1000,FLETCHING:1000,SLAYER:1000,WOODCUTTING:2500", "THE_RESTLESS_GHOST,ERNEST_THE_CHICKEN,PRIEST_IN_PERIL", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ANOTHER_SLICE_OF_HAM", true, "ATTACK:15,PRAYER:25", "MINING:3000,PRAYER:3000", "DEATH_TO_THE_DORGESHUUN,THE_GIANT_DWARF,THE_DIG_SITE", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("AT_FIRST_LIGHT", true, "HUNTER:46,HERBLORE:30,CONSTRUCTION:27", "HUNTER:4500,CONSTRUCTION:800,HERBLORE:500", "CHILDREN_OF_THE_SUN,EAGLES_PEAK", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BARBARIAN_TRAINING", false, "", "", "", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BEAR_YOUR_SOUL", false, "", "", "", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BELOW_ICE_MOUNTAIN", true, "", "", "", 16, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BENEATH_CURSED_SANDS", true, "AGILITY:62,CRAFTING:55,FIREMAKING:55", "AGILITY:50000", "CONTACT", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BETWEEN_A_ROCK", true, "DEFENCE:30,MINING:40,SMITHING:50", "DEFENCE:5000,MINING:5000,SMITHING:5000", "DWARF_CANNON,FISHING_CONTEST", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BIG_CHOMPY_BIRD_HUNTING", true, "RANGED:30,COOKING:30,FLETCHING:5", "FLETCHING:262,COOKING:1470,RANGED:735", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BIOHAZARD", true, "", "THIEVING:1250", "PLAGUE_CITY", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BLACK_KNIGHTS_FORTRESS", true, "", "", "", 12, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("BONE_VOYAGE", true, "", "", "THE_DIG_SITE", 0, 1, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("CABIN_FEVER", true, "AGILITY:42,CRAFTING:45,SMITHING:50,RANGED:40", "SMITHING:7000,CRAFTING:7000,AGILITY:7000", "PIRATES_TREASURE,RUM_DEAL,PRIEST_IN_PERIL", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("CHILDREN_OF_THE_SUN", true, "", "", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("CLIENT_OF_KOUREND", true, "", "", "X_MARKS_THE_SPOT", 0, 1, "", "500 Experience Lamps (Any Skill)"));
        rows.add(new QuestSkillPlanner.QuestData("CLOCK_TOWER", true, "", "", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("COLD_WAR", true, "HUNTER:10,AGILITY:30,CRAFTING:30,CONSTRUCTION:34,THIEVING:15", "CRAFTING:2000,AGILITY:5000,CONSTRUCTION:1500,ATTACK:40", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("CONTACT", true, "", "THIEVING:7000", "PRINCE_ALI_RESCUE,ICTHLARINS_LITTLE_HELPER", 0, 1, "", "7,000 Experience Lamps (Combat Skills)"));
        rows.add(new QuestSkillPlanner.QuestData("COOKS_ASSISTANT", true, "", "COOKING:300", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("CREATURE_OF_FENKENSTRAIN", true, "CRAFTING:20,THIEVING:25", "THIEVING:1000", "PRIEST_IN_PERIL,THE_RESTLESS_GHOST", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("CURRENT_AFFAIRS", true, "SAILING:22,FISHING:10", "SAILING:1400,FISHING:1000", "PANDEMONIUM", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("CURSE_OF_THE_EMPTY_LORD", false, "", "", "DESERT_TREASURE_I,THE_RESTLESS_GHOST", 0, 0, "Partial quest access planned conservatively as completion.", "10,000 Experience Lamp (Any skill over level 50)."));
        rows.add(new QuestSkillPlanner.QuestData("DADDYS_HOME", false, "", "CONSTRUCTION:400", "", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DARKNESS_OF_HALLOWVALE", true, "CONSTRUCTION:5,MINING:20,THIEVING:22,AGILITY:26,CRAFTING:32,MAGIC:33,STRENGTH:40", "AGILITY:7000,THIEVING:6000,CONSTRUCTION:2000", "IN_AID_OF_THE_MYREQUE", 0, 2, "", "2,000 Experience Tomes (Any skill over level 30)."));
        rows.add(new QuestSkillPlanner.QuestData("DEATH_ON_THE_ISLE", true, "THIEVING:34,AGILITY:32", "THIEVING:10000,AGILITY:7500,CRAFTING:5000", "CHILDREN_OF_THE_SUN", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DEATH_PLATEAU", true, "", "ATTACK:3000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DEATH_TO_THE_DORGESHUUN", true, "AGILITY:23,THIEVING:23", "THIEVING:2000,RANGED:2000", "THE_LOST_TRIBE", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DEFENDER_OF_VARROCK", true, "SMITHING:55,HUNTER:52", "SMITHING:15000,HUNTER:15000", "SHIELD_OF_ARRAV,TEMPLE_OF_IKOV,BELOW_ICE_MOUNTAIN,FAMILY_CREST,GARDEN_OF_TRANQUILLITY,WHAT_LIES_BELOW,ROMEO__JULIET,DEMON_SLAYER", 0, 2, "", "5000 exp lamp and 5 kudos from Historian Minas"));
        rows.add(new QuestSkillPlanner.QuestData("DEMON_SLAYER", true, "", "", "", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DESERT_TREASURE_I", true, "THIEVING:53,MAGIC:50,FIREMAKING:50,SLAYER:10", "MAGIC:20000", "THE_DIG_SITE,TEMPLE_OF_IKOV,THE_TOURIST_TRAP,TROLL_STRONGHOLD,PRIEST_IN_PERIL,WATERFALL_QUEST,PLAGUE_CITY", 0, 3, "Partial quest access planned conservatively as completion. Alternative requirements use conservative skill levels.", ""));
        rows.add(new QuestSkillPlanner.QuestData("DESERT_TREASURE_II__THE_FALLEN_EMPIRE", true, "MAGIC:75,FIREMAKING:75,THIEVING:70,HERBLORE:62,RUNECRAFT:60,CONSTRUCTION:60", "", "DESERT_TREASURE_I,SECRETS_OF_THE_NORTH,ENAKHRAS_LAMENT,TEMPLE_OF_THE_EYE,THE_GARDEN_OF_DEATH,BELOW_ICE_MOUNTAIN,HIS_FAITHFUL_SERVANTS", 0, 5, "Check quest guide for access, items and other requirements.", "Ancient Lamp (100k exp in a combat skill)"));
        rows.add(new QuestSkillPlanner.QuestData("DEVIOUS_MINDS", true, "SMITHING:65,RUNECRAFT:50,FLETCHING:50", "FLETCHING:5000,RUNECRAFT:5000,SMITHING:6500", "WANTED,TROLL_STRONGHOLD,DORICS_QUEST,ENTER_THE_ABYSS", 0, 1, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("DORICS_QUEST", true, "", "MINING:1300", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DRAGON_SLAYER_I", true, "", "STRENGTH:18650,DEFENCE:18650", "", 32, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DRAGON_SLAYER_II", true, "MAGIC:75,SMITHING:70,MINING:68,CRAFTING:62,AGILITY:60,THIEVING:60,CONSTRUCTION:50,HITPOINTS:50", "SMITHING:80000,MINING:60000,AGILITY:50000,THIEVING:50000", "LEGENDS_QUEST,DREAM_MENTOR,A_TAIL_OF_TWO_CATS,ANIMAL_MAGNETISM,GHOSTS_AHOY,BONE_VOYAGE,CLIENT_OF_KOUREND", 200, 5, "Check quest guide for access, items and other requirements.", "25,000 Experience Tome (Any Combat Skill)."));
        rows.add(new QuestSkillPlanner.QuestData("DREAM_MENTOR", true, "", "HITPOINTS:15000,MAGIC:10000", "LUNAR_DIPLOMACY,EADGARS_RUSE", 0, 2, "Combat level 85 also required.", "15,000 Experience Lamp (Combat, No Prayer or Attack)"));
        rows.add(new QuestSkillPlanner.QuestData("DRUIDIC_RITUAL", true, "", "HERBLORE:250", "", 0, 4, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("DWARF_CANNON", true, "", "CRAFTING:750", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("EADGARS_RUSE", true, "HERBLORE:31", "HERBLORE:11000", "DRUIDIC_RITUAL,TROLL_STRONGHOLD", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("EAGLES_PEAK", true, "HUNTER:27", "HUNTER:2500", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ELEMENTAL_WORKSHOP_I", true, "MINING:20,SMITHING:20,CRAFTING:20", "CRAFTING:5000,SMITHING:5000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ELEMENTAL_WORKSHOP_II", true, "MAGIC:20,SMITHING:30", "CRAFTING:7500,SMITHING:7500", "ELEMENTAL_WORKSHOP_I", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ENAKHRAS_LAMENT", true, "CRAFTING:50,FIREMAKING:45,PRAYER:43,MAGIC:39", "CRAFTING:7000,MINING:7000,FIREMAKING:7000,MAGIC:7000", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ENLIGHTENED_JOURNEY", true, "FIREMAKING:20,FARMING:30,CRAFTING:36", "CRAFTING:2000,FARMING:3000,WOODCUTTING:1500,FIREMAKING:4000", "", 20, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ENTER_THE_ABYSS", false, "", "RUNECRAFT:1000", "RUNE_MYSTERIES", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ERNEST_THE_CHICKEN", true, "", "", "", 0, 4, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ETHICALLY_ACQUIRED_ANTIQUITIES", true, "THIEVING:25", "THIEVING:6000", "CHILDREN_OF_THE_SUN,SHIELD_OF_ARRAV", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FAIRYTALE_I__GROWING_PAINS", true, "", "FARMING:3500,ATTACK:2000,MAGIC:1000", "LOST_CITY,NATURE_SPIRIT", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FAIRYTALE_II__CURE_A_QUEEN", true, "THIEVING:40,FARMING:49,HERBLORE:57", "HERBLORE:3500,THIEVING:2500", "FAIRYTALE_I__GROWING_PAINS", 0, 2, "", "2,500 Experience Lamp (Any skill over level 30.)"));
        rows.add(new QuestSkillPlanner.QuestData("FALLEN_FROM_GRACE", true, "SAILING:62,CRAFTING:60,RUNECRAFT:47,MINING:53", "CRAFTING:10000,SAILING:12500,MINING:5000,RUNECRAFT:5000", "PANDEMONIUM", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FAMILY_CREST", true, "MINING:40,SMITHING:40,MAGIC:59,CRAFTING:40", "", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FAMILY_PEST", false, "", "", "FAMILY_CREST", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FIGHT_ARENA", true, "", "ATTACK:12175,THIEVING:2175", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FISHING_CONTEST", true, "FISHING:10", "FISHING:2437", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("FORGETTABLE_TALE", true, "COOKING:22,FARMING:17", "COOKING:5000,FARMING:5000", "THE_GIANT_DWARF,FISHING_CONTEST", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("GARDEN_OF_TRANQUILLITY", true, "FARMING:25", "FARMING:5000", "CREATURE_OF_FENKENSTRAIN", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("GERTRUDES_CAT", true, "", "COOKING:1525", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("GETTING_AHEAD", true, "CRAFTING:30,CONSTRUCTION:26", "CRAFTING:4000,CONSTRUCTION:3200", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("GHOSTS_AHOY", true, "AGILITY:25,COOKING:20", "PRAYER:2400", "PRIEST_IN_PERIL,THE_RESTLESS_GHOST", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("GOBLIN_DIPLOMACY", true, "", "CRAFTING:200", "", 0, 5, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("GRIM_TALES", true, "FARMING:45,HERBLORE:52,THIEVING:58,AGILITY:59,WOODCUTTING:71", "FARMING:10000,HERBLORE:15000,HITPOINTS:5000,WOODCUTTING:60000,AGILITY:25000,THIEVING:25000", "WITCHS_HOUSE", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("HAUNTED_MINE", true, "CRAFTING:35", "STRENGTH:22000", "PRIEST_IN_PERIL", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("HAZEEL_CULT", true, "", "THIEVING:1500", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("HEROES_QUEST", true, "COOKING:53,FISHING:53,HERBLORE:25,MINING:50", "ATTACK:3075,DEFENCE:3075,STRENGTH:3075,RANGED:2075,HITPOINTS:3075,FISHING:2725,COOKING:2825,WOODCUTTING:1575,FIREMAKING:1575,SMITHING:2275,MINING:2275,HERBLORE:1325", "SHIELD_OF_ARRAV,LOST_CITY,MERLINS_CRYSTAL,DRAGON_SLAYER_I", 55, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("HIS_FAITHFUL_SERVANTS", false, "", "PRAYER:20000", "PRIEST_IN_PERIL", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("HOLY_GRAIL", true, "ATTACK:20", "PRAYER:11000,DEFENCE:15300", "MERLINS_CRYSTAL", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("HOPESPEARS_WILL", false, "PRAYER:50", "PRAYER:38750", "THE_RESTLESS_GHOST,DESERT_TREASURE_I,FAIRYTALE_II__CURE_A_QUEEN,LAND_OF_THE_GOBLINS", 0, 0, "Partial quest access planned conservatively as completion.", ""));
        rows.add(new QuestSkillPlanner.QuestData("HORROR_FROM_THE_DEEP", true, "AGILITY:35", "MAGIC:4662,STRENGTH:4662,RANGED:4662", "ALFRED_GRIMHANDS_BARCRAWL", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ICTHLARINS_LITTLE_HELPER", true, "", "THIEVING:4500,AGILITY:4000,WOODCUTTING:4000", "GERTRUDES_CAT", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("IMP_CATCHER", true, "", "MAGIC:875", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("IN_AID_OF_THE_MYREQUE", true, "CRAFTING:25,MINING:15,MAGIC:7", "ATTACK:2000,STRENGTH:2000,CRAFTING:2000,DEFENCE:2000", "IN_SEARCH_OF_THE_MYREQUE", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("IN_SEARCH_OF_KNOWLEDGE", false, "", "", "", 0, 0, "", "10,000 Experience Lamp (any skill over level 40)."));
        rows.add(new QuestSkillPlanner.QuestData("IN_SEARCH_OF_THE_MYREQUE", true, "AGILITY:25", "ATTACK:600,DEFENCE:600,STRENGTH:600,HITPOINTS:600,CRAFTING:600", "NATURE_SPIRIT", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("JUNGLE_POTION", true, "HERBLORE:3", "HERBLORE:775", "DRUIDIC_RITUAL", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("KINGS_RANSOM", true, "MAGIC:45,DEFENCE:65", "DEFENCE:33000,MAGIC:5000", "BLACK_KNIGHTS_FORTRESS,HOLY_GRAIL,MURDER_MYSTERY,ONE_SMALL_FAVOUR", 0, 1, "", "5,000 Experience Lamp (any skill over 50)."));
        rows.add(new QuestSkillPlanner.QuestData("LAIR_OF_TARN_RAZORLOR", false, "SLAYER:40", "SLAYER:5000", "HAUNTED_MINE", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("LAND_OF_THE_GOBLINS", true, "AGILITY:38,FISHING:40,THIEVING:45,HERBLORE:48", "AGILITY:8000,FISHING:8000,THIEVING:8000,HERBLORE:8000", "ANOTHER_SLICE_OF_HAM,FISHING_CONTEST", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("LEGENDS_QUEST", true, "AGILITY:50,CRAFTING:50,HERBLORE:45,MAGIC:56,MINING:52,PRAYER:42,SMITHING:50,STRENGTH:50,THIEVING:50,WOODCUTTING:50", "", "FAMILY_CREST,HEROES_QUEST,SHILO_VILLAGE,UNDERGROUND_PASS,WATERFALL_QUEST", 107, 4, "", "30,000 experience in four skills of your choice (limited to Attack, Defence, Strength, Hitpoints, Prayer, Magic, Woodcutting, Crafting, Smithing, Herblore, Agility or Thieving"));
        rows.add(new QuestSkillPlanner.QuestData("LOST_CITY", true, "CRAFTING:31,WOODCUTTING:36", "", "", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("LUNAR_DIPLOMACY", true, "HERBLORE:5,CRAFTING:61,DEFENCE:40,FIREMAKING:49,MAGIC:65,MINING:60,WOODCUTTING:55", "MAGIC:5000,RUNECRAFT:5000", "THE_FREMENNIK_TRIALS,LOST_CITY,RUNE_MYSTERIES,SHILO_VILLAGE", 0, 2, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("MAGE_ARENA_I", false, "MAGIC:60", "", "", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MAGE_ARENA_II", false, "MAGIC:75", "", "MAGE_ARENA_I", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MAKING_FRIENDS_WITH_MY_ARM", true, "FIREMAKING:66,MINING:72,CONSTRUCTION:35,AGILITY:68", "CONSTRUCTION:10000,FIREMAKING:40000,MINING:50000,AGILITY:50000", "MY_ARMS_BIG_ADVENTURE,SWAN_SONG,COLD_WAR,ROMEO__JULIET", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MAKING_HISTORY", true, "", "CRAFTING:1000,PRAYER:1000", "PRIEST_IN_PERIL,THE_RESTLESS_GHOST", 0, 3, "Partial quest access planned conservatively as completion.", ""));
        rows.add(new QuestSkillPlanner.QuestData("MEAT_AND_GREET", true, "", "COOKING:8000", "CHILDREN_OF_THE_SUN", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MERLINS_CRYSTAL", true, "", "", "", 0, 6, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MISTHALIN_MYSTERY", true, "", "CRAFTING:600", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MONKEY_MADNESS_I", true, "", "", "THE_GRAND_TREE,TREE_GNOME_VILLAGE", 0, 3, "", "55,000 Experience Combat Lamp (Over multiple Skills)"));
        rows.add(new QuestSkillPlanner.QuestData("MONKEY_MADNESS_II", true, "SLAYER:69,CRAFTING:70,HUNTER:60,AGILITY:55,THIEVING:55,FIREMAKING:60", "SLAYER:80000,AGILITY:60000,THIEVING:50000,HUNTER:50000", "ENLIGHTENED_JOURNEY,THE_EYES_OF_GLOUPHRIE,TROLL_STRONGHOLD,WATCHTOWER,RECIPE_FOR_DISASTER", 0, 4, "Check quest guide for access, items and other requirements.", "50,000 Experience Lamps (Any Combat Skill)"));
        rows.add(new QuestSkillPlanner.QuestData("MONKS_FRIEND", true, "", "WOODCUTTING:2000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MOUNTAIN_DAUGHTER", true, "AGILITY:20", "ATTACK:1000,PRAYER:2000", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MOURNINGS_END_PART_I", true, "RANGED:60,THIEVING:50", "THIEVING:40000,HITPOINTS:25000", "ROVING_ELVES,BIG_CHOMPY_BIRD_HUNTING,SHEEP_HERDER", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MOURNINGS_END_PART_II", true, "", "AGILITY:60000", "MOURNINGS_END_PART_I", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MURDER_MYSTERY", true, "", "CRAFTING:1406", "", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("MY_ARMS_BIG_ADVENTURE", true, "WOODCUTTING:10,FARMING:29", "HERBLORE:10000,FARMING:5000", "EADGARS_RUSE,THE_FEUD,JUNGLE_POTION", 0, 1, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("NATURE_SPIRIT", true, "", "CRAFTING:3000,DEFENCE:2000,HITPOINTS:2000", "THE_RESTLESS_GHOST,PRIEST_IN_PERIL", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("OBSERVATORY_QUEST", true, "", "CRAFTING:2250", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("OLAFS_QUEST", true, "FIREMAKING:40,WOODCUTTING:50", "DEFENCE:12000", "THE_FREMENNIK_TRIALS", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ONE_SMALL_FAVOUR", true, "AGILITY:36,CRAFTING:25,HERBLORE:18,SMITHING:30", "", "RUNE_MYSTERIES,DRUIDIC_RITUAL,SHILO_VILLAGE", 0, 2, "", "10,000 Experience Lamps (Any skill over level 30)"));
        rows.add(new QuestSkillPlanner.QuestData("PANDEMONIUM", true, "", "SAILING:300", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("PERILOUS_MOONS", true, "SLAYER:48,HUNTER:20,FISHING:20,RUNECRAFT:20,CONSTRUCTION:10", "SLAYER:40000,RUNECRAFT:5000,HUNTER:5000,FISHING:5000", "TWILIGHTS_PROMISE", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("PIRATES_TREASURE", true, "", "", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("PLAGUE_CITY", true, "", "MINING:2425", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("PRIEST_IN_PERIL", true, "", "PRAYER:1406", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("PRINCE_ALI_RESCUE", true, "", "", "", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("PRYING_TIMES", true, "", "SAILING:800,SMITHING:1000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("RAG_AND_BONE_MAN_I", true, "", "COOKING:500,PRAYER:500", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("RAG_AND_BONE_MAN_II", true, "SLAYER:40,DEFENCE:20", "PRAYER:5000", "RAG_AND_BONE_MAN_I,SKIPPY_AND_THE_MOGRES,CREATURE_OF_FENKENSTRAIN,ZOGRE_FLESH_EATERS", 0, 1, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("RATCATCHERS", true, "", "THIEVING:4500", "ICTHLARINS_LITTLE_HELPER,THE_GIANT_DWARF", 0, 2, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("RECIPE_FOR_DISASTER", true, "COOKING:70,CRAFTING:42,AGILITY:48,FIREMAKING:20", "COOKING:28000,SLAYER:1000,FARMING:1000,CRAFTING:3500,FISHING:1000,SMITHING:1000,MAGIC:2500,AGILITY:10000,HITPOINTS:4000,WOODCUTTING:1500,RANGED:1500", "COOKS_ASSISTANT,FISHING_CONTEST,GOBLIN_DIPLOMACY,RUM_DEAL,BIG_CHOMPY_BIRD_HUNTING,BIOHAZARD,DEMON_SLAYER,MURDER_MYSTERY,NATURE_SPIRIT,WITCHS_HOUSE,GERTRUDES_CAT,SHADOW_OF_THE_STORM,MONKEY_MADNESS_I,FAMILY_CREST,HEROES_QUEST,SHILO_VILLAGE,UNDERGROUND_PASS,WATERFALL_QUEST,DESERT_TREASURE_I,HORROR_FROM_THE_DEEP,LEGENDS_QUEST", 175, 10, "Check quest guide for access, items and other requirements. Partial quest access planned conservatively as completion. Alternative requirements use conservative skill levels.", "20,000 Experience Lamp (Any skill over level 50)"));
        rows.add(new QuestSkillPlanner.QuestData("RECRUITMENT_DRIVE", true, "", "PRAYER:1000,AGILITY:1000,HERBLORE:1000", "BLACK_KNIGHTS_FORTRESS,DRUIDIC_RITUAL", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("REGICIDE", true, "CRAFTING:10,AGILITY:56", "AGILITY:13750", "UNDERGROUND_PASS", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ROMEO__JULIET", true, "", "", "", 0, 5, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ROVING_ELVES", true, "AGILITY:56", "STRENGTH:10000", "REGICIDE,WATERFALL_QUEST", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("ROYAL_TROUBLE", true, "AGILITY:40,SLAYER:40", "AGILITY:5000,SLAYER:5000,HITPOINTS:5000", "THRONE_OF_MISCELLANIA", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("RUM_DEAL", true, "CRAFTING:42,FISHING:50,FARMING:40,PRAYER:47,SLAYER:42", "FISHING:7000,PRAYER:7000,FARMING:7000", "ZOGRE_FLESH_EATERS,PRIEST_IN_PERIL", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("RUNE_MYSTERIES", true, "", "", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SCORPION_CATCHER", true, "PRAYER:31", "STRENGTH:6625", "ALFRED_GRIMHANDS_BARCRAWL", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SCRAMBLED", true, "CONSTRUCTION:38,COOKING:36,SMITHING:35", "CONSTRUCTION:5000,COOKING:5000,SMITHING:5000", "CHILDREN_OF_THE_SUN", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SEA_SLUG", true, "FIREMAKING:30", "FISHING:7175", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SECRETS_OF_THE_NORTH", true, "AGILITY:69,THIEVING:64,HUNTER:56", "AGILITY:60000,THIEVING:50000,HUNTER:40000", "MAKING_FRIENDS_WITH_MY_ARM,THE_GENERALS_SHADOW,DEVIOUS_MINDS,HAZEEL_CULT", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SHADES_OF_MORTTON", true, "CRAFTING:20,HERBLORE:15,FIREMAKING:5", "CRAFTING:2000,HERBLORE:2000", "PRIEST_IN_PERIL", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SHADOW_OF_THE_STORM", true, "CRAFTING:30", "", "THE_GOLEM,DEMON_SLAYER", 0, 1, "", "10,000 Experience Lamp (Any combat skill except Prayer)"));
        rows.add(new QuestSkillPlanner.QuestData("SHADOWS_OF_CUSTODIA", true, "SLAYER:54,FISHING:45,CONSTRUCTION:41,HUNTER:36", "SLAYER:10000,HUNTER:4000,FISHING:3000,CONSTRUCTION:3000", "CHILDREN_OF_THE_SUN", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SHEEP_HERDER", true, "", "", "", 0, 4, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SHEEP_SHEARER", true, "", "CRAFTING:150", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SHIELD_OF_ARRAV", true, "", "", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SHILO_VILLAGE", true, "CRAFTING:20,AGILITY:32", "CRAFTING:3875", "JUNGLE_POTION", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SINS_OF_THE_FATHER", true, "WOODCUTTING:62,FLETCHING:60,CRAFTING:56,AGILITY:52,ATTACK:50,SLAYER:50,MAGIC:49", "", "VAMPYRE_SLAYER,A_TASTE_OF_HOPE", 0, 2, "", "15,000 Experience Tomes (Any skill above 60)"));
        rows.add(new QuestSkillPlanner.QuestData("SKIPPY_AND_THE_MOGRES", false, "COOKING:20", "", "", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SLEEPING_GIANTS", true, "SMITHING:15", "SMITHING:6000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SONG_OF_THE_ELVES", true, "AGILITY:70,CONSTRUCTION:70,FARMING:70,HERBLORE:70,HUNTER:70,MINING:70,SMITHING:70,WOODCUTTING:70", "AGILITY:40000,CONSTRUCTION:40000,FARMING:40000,HERBLORE:40000,HUNTER:40000,MINING:40000,SMITHING:40000,WOODCUTTING:40000", "MOURNINGS_END_PART_II,MAKING_HISTORY", 0, 4, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("SPIRITS_OF_THE_ELID", true, "MAGIC:33,RANGED:37,MINING:37,THIEVING:37", "PRAYER:8000,THIEVING:1000,MAGIC:1000", "", 0, 2, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("SWAN_SONG", true, "MAGIC:66,COOKING:62,FISHING:62,SMITHING:45,CRAFTING:40,FIREMAKING:42", "MAGIC:15000,PRAYER:10000,FISHING:50000", "ONE_SMALL_FAVOUR,GARDEN_OF_TRANQUILLITY", 100, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TAI_BWO_WANNAI_TRIO", true, "FIREMAKING:30,AGILITY:15,COOKING:30,FISHING:5", "COOKING:5000,FISHING:5000,ATTACK:2500,STRENGTH:2500", "JUNGLE_POTION", 0, 2, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("TALE_OF_THE_RIGHTEOUS", true, "STRENGTH:16,MINING:10", "", "X_MARKS_THE_SPOT,CLIENT_OF_KOUREND", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TEARS_OF_GUTHIX", true, "FIREMAKING:49,CRAFTING:20,MINING:20", "CRAFTING:1000", "", 43, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TEMPLE_OF_IKOV", true, "THIEVING:42,RANGED:40", "RANGED:10500,FLETCHING:8000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TEMPLE_OF_THE_EYE", true, "RUNECRAFT:10", "RUNECRAFT:9210", "ENTER_THE_ABYSS", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_ASCENT_OF_ARCEUUS", true, "HUNTER:12", "HUNTER:1500,RUNECRAFT:500", "X_MARKS_THE_SPOT,CLIENT_OF_KOUREND", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_BLOOD_MOON_RISES", true, "SLAYER:74,WOODCUTTING:74,SMITHING:72,COOKING:72,FLETCHING:70,MINING:66,HUNTER:65,CRAFTING:64,HERBLORE:64,MAGIC:57", "", "A_NIGHT_AT_THE_THEATRE,SINS_OF_THE_FATHER", 0, 4, "", "30,000 Experience Tomes (Any skill above 70)"));
        rows.add(new QuestSkillPlanner.QuestData("THE_CORSAIR_CURSE", true, "", "", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_CURSE_OF_ARRAV", true, "MINING:64,RANGED:62,THIEVING:62,AGILITY:61,STRENGTH:58,SLAYER:37", "MINING:40000,THIEVING:40000,AGILITY:40000", "DEFENDER_OF_VARROCK,TROLL_ROMANCE", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_DEPTHS_OF_DESPAIR", true, "AGILITY:18", "AGILITY:1500", "CLIENT_OF_KOUREND,X_MARKS_THE_SPOT", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_DIG_SITE", true, "AGILITY:10,HERBLORE:10,THIEVING:25", "MINING:15300,HERBLORE:2000", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_ENCHANTED_KEY", false, "", "", "MAKING_HISTORY", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_EYES_OF_GLOUPHRIE", true, "CONSTRUCTION:5,MAGIC:46", "MAGIC:12000,WOODCUTTING:2500,RUNECRAFT:6000,CONSTRUCTION:250", "THE_GRAND_TREE", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_FEUD", true, "THIEVING:30", "THIEVING:15000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_FINAL_DAWN", true, "THIEVING:66,FLETCHING:52,RUNECRAFT:52", "THIEVING:55000,FLETCHING:25000,RUNECRAFT:25000", "THE_HEART_OF_DARKNESS,PERILOUS_MOONS", 0, 3, "", "55,000 Experience Lamps (Combat Skills)"));
        rows.add(new QuestSkillPlanner.QuestData("THE_FORSAKEN_TOWER", true, "", "MINING:500,SMITHING:500", "X_MARKS_THE_SPOT,CLIENT_OF_KOUREND", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_FREMENNIK_EXILES", true, "CRAFTING:65,SLAYER:60,SMITHING:60,FISHING:60,MINING:60,RUNECRAFT:55", "SLAYER:50000,CRAFTING:50000,RUNECRAFT:30000", "THE_FREMENNIK_ISLES,LUNAR_DIPLOMACY,MOUNTAIN_DAUGHTER,HEROES_QUEST", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_FREMENNIK_ISLES", true, "AGILITY:40,CONSTRUCTION:20,WOODCUTTING:56,CRAFTING:46", "CONSTRUCTION:5000,CRAFTING:5000,WOODCUTTING:10000", "THE_FREMENNIK_TRIALS", 0, 1, "Alternative requirements use conservative skill levels.", "10,000 Exp. Lamp (Combat)"));
        rows.add(new QuestSkillPlanner.QuestData("THE_FREMENNIK_TRIALS", true, "FLETCHING:25,WOODCUTTING:40,CRAFTING:40", "AGILITY:2812,ATTACK:2812,CRAFTING:2812,DEFENCE:2812,FISHING:2812,FLETCHING:2812,HITPOINTS:2812,STRENGTH:2812,THIEVING:2812,WOODCUTTING:2812", "", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_GARDEN_OF_DEATH", true, "FARMING:20", "FARMING:10000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_GENERALS_SHADOW", false, "", "SLAYER:2000", "CURSE_OF_THE_EMPTY_LORD,FIGHT_ARENA", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_GIANT_DWARF", true, "CRAFTING:12,FIREMAKING:16,MAGIC:33,THIEVING:14", "MINING:2500,SMITHING:2500,CRAFTING:2500,MAGIC:1500,THIEVING:1500,FIREMAKING:1500", "", 0, 2, "Check quest guide for access, items and other requirements.", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_GOLEM", true, "CRAFTING:20,THIEVING:25", "THIEVING:1000,CRAFTING:1000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_GRAND_TREE", true, "AGILITY:25", "ATTACK:18400,AGILITY:7900,MAGIC:2150", "", 0, 5, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_GREAT_BRAIN_ROBBERY", true, "CRAFTING:16,CONSTRUCTION:30,PRAYER:50", "PRAYER:6000,CRAFTING:2000,CONSTRUCTION:2000", "CREATURE_OF_FENKENSTRAIN,RUM_DEAL,CABIN_FEVER,RECIPE_FOR_DISASTER", 0, 2, "Check quest guide for access, items and other requirements.", "5,000 Exp Reward Lamp (Any skill above 30)"));
        rows.add(new QuestSkillPlanner.QuestData("THE_HAND_IN_THE_SAND", true, "THIEVING:17,CRAFTING:49", "THIEVING:1000,CRAFTING:9000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_HEART_OF_DARKNESS", true, "MINING:55,THIEVING:48,SLAYER:48,AGILITY:46", "MINING:8000,THIEVING:8000,SLAYER:8000,AGILITY:8000", "TWILIGHTS_PROMISE", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_IDES_OF_MILK", true, "", "", "", 0, 1, "", "Cow bell amulet and magic lamp (1,000 XP combat/Prayer) from Gillie Groats"));
        rows.add(new QuestSkillPlanner.QuestData("THE_KNIGHTS_SWORD", true, "MINING:10", "SMITHING:12725", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_LOST_TRIBE", true, "AGILITY:13,THIEVING:13,MINING:17", "MINING:3000", "GOBLIN_DIPLOMACY,RUNE_MYSTERIES", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_PATH_OF_GLOUPHRIE", true, "STRENGTH:60,SLAYER:56,THIEVING:56,RANGED:47,AGILITY:45", "", "THE_EYES_OF_GLOUPHRIE,WATERFALL_QUEST,TREE_GNOME_VILLAGE", 0, 2, "", "30000 STRENGTH XP lamp (not deducted); 20000 SLAYER XP lamp (not deducted); 5000 THIEVING XP lamp (not deducted); 5000 MAGIC XP lamp (not deducted)"));
        rows.add(new QuestSkillPlanner.QuestData("THE_QUEEN_OF_THIEVES", true, "THIEVING:20", "THIEVING:2000", "CLIENT_OF_KOUREND,X_MARKS_THE_SPOT", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_RED_REEF", true, "SAILING:52,SMITHING:48", "SAILING:15000,SMITHING:5000", "TROUBLED_TORTUGANS", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_RESTLESS_GHOST", true, "", "PRAYER:1125", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE", true, "WOODCUTTING:15", "WOODCUTTING:2000", "CHILDREN_OF_THE_SUN", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_SLUG_MENACE", true, "CRAFTING:30,RUNECRAFT:30,SLAYER:30,THIEVING:30", "RUNECRAFT:3500,CRAFTING:3500,THIEVING:3500", "WANTED,SEA_SLUG", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("THE_TOURIST_TRAP", true, "FLETCHING:10,SMITHING:20", "", "", 0, 2, "", "4,650 Exp. Lamps (Agility, Fletching, Smithing or Thieving)"));
        rows.add(new QuestSkillPlanner.QuestData("THRONE_OF_MISCELLANIA", true, "WOODCUTTING:45,FARMING:10,MINING:30,SMITHING:35", "", "HEROES_QUEST,THE_FREMENNIK_TRIALS", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TOWER_OF_LIFE", true, "CONSTRUCTION:10", "CONSTRUCTION:1000,CRAFTING:500,THIEVING:500", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TREE_GNOME_VILLAGE", true, "", "ATTACK:11450", "", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TRIBAL_TOTEM", true, "THIEVING:21", "THIEVING:1775", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TROLL_ROMANCE", true, "AGILITY:28", "AGILITY:8000,STRENGTH:4000", "TROLL_STRONGHOLD", 0, 2, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TROLL_STRONGHOLD", true, "AGILITY:15", "", "DEATH_PLATEAU", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TROUBLED_TORTUGANS", true, "SAILING:45,SLAYER:51,HUNTER:45,CONSTRUCTION:48,WOODCUTTING:40,CRAFTING:34", "SAILING:10000,SLAYER:8000", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("TWILIGHTS_PROMISE", true, "", "THIEVING:3000", "CHILDREN_OF_THE_SUN", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("UNDERGROUND_PASS", true, "RANGED:25", "AGILITY:3000,ATTACK:3000", "BIOHAZARD", 0, 5, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("VALE_TOTEMS", false, "FLETCHING:20", "", "CHILDREN_OF_THE_SUN", 0, 0, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("VAMPYRE_SLAYER", true, "", "ATTACK:4825", "", 0, 3, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("WANTED", true, "", "SLAYER:5000", "ENTER_THE_ABYSS,RECRUITMENT_DRIVE,THE_LOST_TRIBE,PRIEST_IN_PERIL", 32, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("WATCHTOWER", true, "MAGIC:15,THIEVING:15,AGILITY:25,HERBLORE:14,MINING:40", "MAGIC:15250", "", 0, 4, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("WATERFALL_QUEST", true, "", "STRENGTH:13750,ATTACK:13750", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("WHAT_LIES_BELOW", true, "MINING:42,RUNECRAFT:35", "RUNECRAFT:8000,DEFENCE:2000", "RUNE_MYSTERIES", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("WHILE_GUTHIX_SLEEPS", true, "THIEVING:72,MAGIC:67,AGILITY:66,HERBLORE:65,FARMING:65,HUNTER:62", "THIEVING:80000,FARMING:75000,HERBLORE:75000,HUNTER:50000", "DEFENDER_OF_VARROCK,THE_PATH_OF_GLOUPHRIE,FIGHT_ARENA,DREAM_MENTOR,THE_HAND_IN_THE_SAND,WANTED,TEMPLE_OF_THE_EYE,A_TAIL_OF_TWO_CATS,TEARS_OF_GUTHIX,NATURE_SPIRIT", 180, 5, "Warriors Guild access also required.", ""));
        rows.add(new QuestSkillPlanner.QuestData("WITCHS_HOUSE", true, "", "HITPOINTS:6325", "", 0, 4, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("WITCHS_POTION", true, "", "MAGIC:325", "", 0, 1, "", ""));
        rows.add(new QuestSkillPlanner.QuestData("X_MARKS_THE_SPOT", true, "", "", "", 0, 1, "", "300 Exp. Lamp (Any Skill)"));
        rows.add(new QuestSkillPlanner.QuestData("ZOGRE_FLESH_EATERS", true, "SMITHING:4,HERBLORE:8,RANGED:30", "FLETCHING:2000,RANGED:2000,HERBLORE:2000", "BIG_CHOMPY_BIRD_HUNTING,JUNGLE_POTION", 0, 1, "", ""));
        return Collections.unmodifiableList(rows);
    }
}
